/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ChainPass {
      
    export type EventStruct = {name: string, fee: BigNumberish, maxParticipants: BigNumberish, deadline: BigNumberish, organizer: AddressLike, isOpen: boolean, participantCount: BigNumberish, fundsWithdrawn: boolean}

    export type EventStructOutput = [name: string, fee: bigint, maxParticipants: bigint, deadline: bigint, organizer: string, isOpen: boolean, participantCount: bigint, fundsWithdrawn: boolean] & {name: string, fee: bigint, maxParticipants: bigint, deadline: bigint, organizer: string, isOpen: boolean, participantCount: bigint, fundsWithdrawn: boolean }
  
    }

  export interface ChainPassInterface extends Interface {
    getFunction(nameOrSignature: "balanceOf" | "balanceOfBatch" | "cancelRegistration" | "closeRegistration" | "createEvent" | "eventCounter" | "eventParticipants" | "events" | "getEventDetails" | "getParticipants" | "hasRegistered" | "isApprovedForAll" | "isRegistered" | "openRegistration" | "owner" | "pauseRegistration" | "registerForEvent" | "renounceOwnership" | "reopenRegistration" | "safeBatchTransferFrom" | "safeTransferFrom" | "setApprovalForAll" | "setURI" | "supportsInterface" | "transferOwnership" | "uri" | "withdrawFunds"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ApprovalForAll" | "EventCreated" | "OwnershipTransferred" | "Registered" | "RegistrationCancelled" | "RegistrationToggled" | "TicketMinted" | "TransferBatch" | "TransferSingle" | "URI"): EventFragment;

    encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOfBatch', values: [AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'cancelRegistration', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'closeRegistration', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createEvent', values: [string, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'eventCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'eventParticipants', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'events', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getEventDetails', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getParticipants', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasRegistered', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isRegistered', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'openRegistration', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pauseRegistration', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerForEvent', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'reopenRegistration', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeBatchTransferFrom', values: [AddressLike, AddressLike, BigNumberish[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setURI', values: [string]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'uri', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawFunds', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOfBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelRegistration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeRegistration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createEvent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'eventCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'eventParticipants', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'events', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEventDetails', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getParticipants', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openRegistration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseRegistration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerForEvent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reopenRegistration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeBatchTransferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uri', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFunds', data: BytesLike): Result;
  }

  
    export namespace ApprovalForAllEvent {
      export type InputTuple = [account: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [account: string, operator: string, approved: boolean];
      export interface OutputObject {account: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EventCreatedEvent {
      export type InputTuple = [eventId: BigNumberish, name: string, organizer: AddressLike, fee: BigNumberish, maxParticipants: BigNumberish, deadline: BigNumberish];
      export type OutputTuple = [eventId: bigint, name: string, organizer: string, fee: bigint, maxParticipants: bigint, deadline: bigint];
      export interface OutputObject {eventId: bigint, name: string, organizer: string, fee: bigint, maxParticipants: bigint, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RegisteredEvent {
      export type InputTuple = [eventId: BigNumberish, participant: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [eventId: bigint, participant: string, tokenId: bigint];
      export interface OutputObject {eventId: bigint, participant: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RegistrationCancelledEvent {
      export type InputTuple = [eventId: BigNumberish, participant: AddressLike, refundAmount: BigNumberish];
      export type OutputTuple = [eventId: bigint, participant: string, refundAmount: bigint];
      export interface OutputObject {eventId: bigint, participant: string, refundAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RegistrationToggledEvent {
      export type InputTuple = [eventId: BigNumberish, isOpen: boolean];
      export type OutputTuple = [eventId: bigint, isOpen: boolean];
      export interface OutputObject {eventId: bigint, isOpen: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TicketMintedEvent {
      export type InputTuple = [tokenId: BigNumberish, owner: AddressLike];
      export type OutputTuple = [tokenId: bigint, owner: string];
      export interface OutputObject {tokenId: bigint, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferBatchEvent {
      export type InputTuple = [operator: AddressLike, from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[]];
      export type OutputTuple = [operator: string, from: string, to: string, ids: bigint[], values: bigint[]];
      export interface OutputObject {operator: string, from: string, to: string, ids: bigint[], values: bigint[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferSingleEvent {
      export type InputTuple = [operator: AddressLike, from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish];
      export type OutputTuple = [operator: string, from: string, to: string, id: bigint, value: bigint];
      export interface OutputObject {operator: string, from: string, to: string, id: bigint, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace URIEvent {
      export type InputTuple = [value: string, id: BigNumberish];
      export type OutputTuple = [value: string, id: bigint];
      export interface OutputObject {value: string, id: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ChainPass extends BaseContract {
    
    connect(runner?: ContractRunner | null): ChainPass;
    waitForDeployment(): Promise<this>;

    interface: ChainPassInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    balanceOf: TypedContractMethod<
      [account: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    balanceOfBatch: TypedContractMethod<
      [accounts: AddressLike[], ids: BigNumberish[], ],
      [bigint[]],
      'view'
    >
    

    
    cancelRegistration: TypedContractMethod<
      [_eventId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    closeRegistration: TypedContractMethod<
      [_eventId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createEvent: TypedContractMethod<
      [_name: string, _fee: BigNumberish, _maxParticipants: BigNumberish, _deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    eventCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    eventParticipants: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    events: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, string, boolean, bigint, boolean] & {name: string, fee: bigint, maxParticipants: bigint, deadline: bigint, organizer: string, isOpen: boolean, participantCount: bigint, fundsWithdrawn: boolean }],
      'view'
    >
    

    
    getEventDetails: TypedContractMethod<
      [_eventId: BigNumberish, ],
      [ChainPass.EventStructOutput],
      'view'
    >
    

    
    getParticipants: TypedContractMethod<
      [_eventId: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    hasRegistered: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [account: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isRegistered: TypedContractMethod<
      [_eventId: BigNumberish, _user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    openRegistration: TypedContractMethod<
      [_eventId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pauseRegistration: TypedContractMethod<
      [_eventId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    registerForEvent: TypedContractMethod<
      [_eventId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    reopenRegistration: TypedContractMethod<
      [_eventId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    safeBatchTransferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    safeTransferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setURI: TypedContractMethod<
      [newuri: string, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    uri: TypedContractMethod<
      [_tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    withdrawFunds: TypedContractMethod<
      [_eventId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOfBatch'): TypedContractMethod<
      [accounts: AddressLike[], ids: BigNumberish[], ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'cancelRegistration'): TypedContractMethod<
      [_eventId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'closeRegistration'): TypedContractMethod<
      [_eventId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createEvent'): TypedContractMethod<
      [_name: string, _fee: BigNumberish, _maxParticipants: BigNumberish, _deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'eventCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'eventParticipants'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'events'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, string, boolean, bigint, boolean] & {name: string, fee: bigint, maxParticipants: bigint, deadline: bigint, organizer: string, isOpen: boolean, participantCount: bigint, fundsWithdrawn: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getEventDetails'): TypedContractMethod<
      [_eventId: BigNumberish, ],
      [ChainPass.EventStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getParticipants'): TypedContractMethod<
      [_eventId: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'hasRegistered'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [account: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRegistered'): TypedContractMethod<
      [_eventId: BigNumberish, _user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'openRegistration'): TypedContractMethod<
      [_eventId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pauseRegistration'): TypedContractMethod<
      [_eventId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerForEvent'): TypedContractMethod<
      [_eventId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reopenRegistration'): TypedContractMethod<
      [_eventId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeBatchTransferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setURI'): TypedContractMethod<
      [newuri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'uri'): TypedContractMethod<
      [_tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawFunds'): TypedContractMethod<
      [_eventId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'EventCreated'): TypedContractEvent<EventCreatedEvent.InputTuple, EventCreatedEvent.OutputTuple, EventCreatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Registered'): TypedContractEvent<RegisteredEvent.InputTuple, RegisteredEvent.OutputTuple, RegisteredEvent.OutputObject>;
getEvent(key: 'RegistrationCancelled'): TypedContractEvent<RegistrationCancelledEvent.InputTuple, RegistrationCancelledEvent.OutputTuple, RegistrationCancelledEvent.OutputObject>;
getEvent(key: 'RegistrationToggled'): TypedContractEvent<RegistrationToggledEvent.InputTuple, RegistrationToggledEvent.OutputTuple, RegistrationToggledEvent.OutputObject>;
getEvent(key: 'TicketMinted'): TypedContractEvent<TicketMintedEvent.InputTuple, TicketMintedEvent.OutputTuple, TicketMintedEvent.OutputObject>;
getEvent(key: 'TransferBatch'): TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
getEvent(key: 'TransferSingle'): TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
getEvent(key: 'URI'): TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;

    filters: {
      
      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'EventCreated(uint256,string,address,uint256,uint256,uint256)': TypedContractEvent<EventCreatedEvent.InputTuple, EventCreatedEvent.OutputTuple, EventCreatedEvent.OutputObject>;
      EventCreated: TypedContractEvent<EventCreatedEvent.InputTuple, EventCreatedEvent.OutputTuple, EventCreatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Registered(uint256,address,uint256)': TypedContractEvent<RegisteredEvent.InputTuple, RegisteredEvent.OutputTuple, RegisteredEvent.OutputObject>;
      Registered: TypedContractEvent<RegisteredEvent.InputTuple, RegisteredEvent.OutputTuple, RegisteredEvent.OutputObject>;
    

      'RegistrationCancelled(uint256,address,uint256)': TypedContractEvent<RegistrationCancelledEvent.InputTuple, RegistrationCancelledEvent.OutputTuple, RegistrationCancelledEvent.OutputObject>;
      RegistrationCancelled: TypedContractEvent<RegistrationCancelledEvent.InputTuple, RegistrationCancelledEvent.OutputTuple, RegistrationCancelledEvent.OutputObject>;
    

      'RegistrationToggled(uint256,bool)': TypedContractEvent<RegistrationToggledEvent.InputTuple, RegistrationToggledEvent.OutputTuple, RegistrationToggledEvent.OutputObject>;
      RegistrationToggled: TypedContractEvent<RegistrationToggledEvent.InputTuple, RegistrationToggledEvent.OutputTuple, RegistrationToggledEvent.OutputObject>;
    

      'TicketMinted(uint256,address)': TypedContractEvent<TicketMintedEvent.InputTuple, TicketMintedEvent.OutputTuple, TicketMintedEvent.OutputObject>;
      TicketMinted: TypedContractEvent<TicketMintedEvent.InputTuple, TicketMintedEvent.OutputTuple, TicketMintedEvent.OutputObject>;
    

      'TransferBatch(address,address,address,uint256[],uint256[])': TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
      TransferBatch: TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
    

      'TransferSingle(address,address,address,uint256,uint256)': TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
      TransferSingle: TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
    

      'URI(string,uint256)': TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
      URI: TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
    
    };
  }