/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ChainPass } from './ChainPass.js';
export * as factories from './factories/index.js';
export { ChainPass__factory } from './factories/ChainPass__factory.js';